services:
  - type: web
    name: entertainment-tadka-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: MAIN_CHANNEL_ID
        value: "-1003181705395"
      - key: SERIAL_CHANNEL_ID
        value: "-1003614546520"
      - key: THEATER_CHANNEL_ID
        value: "-1002831605258"
      - key: BACKUP_CHANNEL_ID
        value: "-1002964109368"
      - key: PRIVATE_CHANNEL_1_ID
        value: "-1003251791991"
      - key: PRIVATE_CHANNEL_2_ID
        value: "-1002337293281"
      - key: REQUEST_GROUP_ID
        value: "-1003083386043"
      - key: ADMIN_ID
        value: "1080317415"
      - key: MAIN_CHANNEL
        value: "@EntertainmentTadka786"
      - key: SERIAL_CHANNEL
        value: "@Entertainment_Tadka_Serial_786"
      - key: THEATER_CHANNEL
        value: "@threater_print_movies"
      - key: BACKUP_CHANNEL
        value: "@ETBackup"
      - key: REQUEST_GROUP
        value: "@EntertainmentTadka7860"
    healthCheckPath: /
    autoDeploy: true